// Provenance emitter — emits prov:wasGeneratedBy + prov:Activity quads
// for any resource that needs build/view-time provenance.
//
// Replaces concept-browser's src/components/concept-rdf/provenance.ts
// (runtime provenance at view-time). Same output shape, but operates
// on standard RDF/JS Quad[] (no RdfGraph abstraction).

import { namedNode, blankNode, literal, quad } from './terms.js';
import { PREFIXES } from './predicates.js';
import { RDF_TYPE, RDFS_LABEL } from './curie.js';
import { deterministicBnodeId } from './bnode-id.js';

const PROV_NS    = PREFIXES.prov;
const DCTERMS_NS = PREFIXES.dcterms;
const XSD_NS     = PREFIXES.xsd;

const PROV = {
  Activity:        `${PROV_NS}Activity`,
  Entity:          `${PROV_NS}Entity`,
  SoftwareAgent:   `${PROV_NS}SoftwareAgent`,
  Agent:           `${PROV_NS}Agent`,
  wasGeneratedBy:  `${PROV_NS}wasGeneratedBy`,
  wasAssociatedWith: `${PROV_NS}wasAssociatedWith`,
  generatedAtTime: `${PROV_NS}generatedAtTime`,
  startedAtTime:   `${PROV_NS}startedAtTime`,
  endedAtTime:     `${PROV_NS}endedAtTime`,
};
const DCTERMS = {
  isVersionOf:  `${DCTERMS_NS}isVersionOf`,
  title:        `${DCTERMS_NS}title`,
};
const FOAF_NS = PREFIXES.foaf ?? 'http://xmlns.com/foaf/0.1/';
const XSD_DATETIME = `${XSD_NS}dateTime`;

/**
 * @typedef {Object} ProvenanceInput
 * @property {string} subjectUri — the resource being provenance-tagged
 * @property {string} serializer — e.g. "concept-browser"
 * @property {string} serializerVersion — e.g. "0.7.66"
 * @property {string} generatedAt — ISO 8601 date-time
 * @property {string} [canonicalUri] — for dcterms:isVersionOf (versions)
 */

/**
 * Emits provenance quads linking subjectUri to a prov:Activity
 * performed by a prov:SoftwareAgent. The activity IRI is relative
 * (under the document base): `activity/serializers/{serializer}/{version}`.
 *
 * Idempotent: same input always produces the same bnode IDs and the
 * same set of quads.
 *
 * @param {ProvenanceInput} input
 * @returns {Generator<import('@rdfjs/dataset').Quad, void, unknown>}
 */
export function* provenanceToQuads(input) {
  if (!input?.subjectUri) throw new Error('provenanceToQuads: subjectUri is required');
  if (!input?.serializer) throw new Error('provenanceToQuads: serializer is required');
  if (!input?.serializerVersion) throw new Error('provenanceToQuads: serializerVersion is required');
  if (!input?.generatedAt) throw new Error('provenanceToQuads: generatedAt is required');

  const subject = namedNode(input.subjectUri);
  const activityIri = namedNode(`activity/serializers/${input.serializer}/${input.serializerVersion}`);

  // Subject is a prov:Entity, generated by the activity, at the timestamp
  yield quad(subject, namedNode(RDF_TYPE), namedNode(PROV.Entity));
  yield quad(subject, namedNode(PROV.wasGeneratedBy), activityIri);
  yield quad(subject, namedNode(PROV.generatedAtTime), literal(input.generatedAt, namedNode(XSD_DATETIME)));

  if (input.canonicalUri && input.canonicalUri !== input.subjectUri) {
    yield quad(subject, namedNode(DCTERMS.isVersionOf), namedNode(input.canonicalUri));
  }

  // Activity is a prov:Activity, associated with the software agent
  yield quad(activityIri, namedNode(RDF_TYPE), namedNode(PROV.Activity));
  yield quad(activityIri, namedNode(RDFS_LABEL), literal(`${input.serializer} ${input.serializerVersion}`));

  // Software agent as a deterministic blank node — same input always
  // produces the same bnode ID so multiple subjects that share a
  // serializer/version collapse to one agent.
  const agentId = deterministicBnodeId('agent', input.serializer, input.serializerVersion);
  const agent = blankNode(`b${agentId}`);
  yield quad(activityIri, namedNode(PROV.wasAssociatedWith), agent);
  yield quad(agent, namedNode(RDF_TYPE), namedNode(PROV.SoftwareAgent));
  yield quad(agent, namedNode(RDF_TYPE), namedNode(PROV.Agent));
  yield quad(agent, namedNode(RDFS_LABEL), literal(input.serializer));
  yield quad(agent, namedNode(`${FOAF_NS}name`), literal(input.serializer));
}
