export { Register, REGISTER_STATUSES } from './register.js';
export { Section, ORDERING_METHODS } from './section.js';
export { resolveColor, isColorPair, validateColor, COLOR_MODES } from './dataset-color.js';
export { GlossaristModel } from './base.js';
export { Concept } from './concept.js';
export { LocalizedConcept } from './localized-concept.js';
export { Designation, Expression, Abbreviation, Symbol, LetterSymbol, GraphicalSymbol } from './designation.js';
export { Citation } from './citation.js';
export { ConceptRef } from './concept-ref.js';
export { ConceptSource } from './concept-source.js';
export { RelatedConcept, RELATIONSHIP_TYPES } from './related-concept.js';
export { DesignationRelationship, DESIGNATION_RELATIONSHIP_TYPES } from './designation-relationship.js';
export { ConceptReference } from './concept-reference.js';
export { ConceptDate, DATE_TYPES } from './concept-date.js';
export { DetailedDefinition } from './detailed-definition.js';
export { Pronunciation } from './pronunciation.js';
export { GrammarInfo, GRAMMAR_GENDERS, GRAMMAR_NUMBERS, GRAMMAR_PARTS_OF_SPEECH } from './grammar-info.js';
export { Locality } from './locality.js';
export { GcrMetadata } from './gcr-metadata.js';
export { GcrStatistics } from './gcr-statistics.js';
export { RegistrableModel } from './registrable.js';
export { NonVerbalEntity } from './non-verbal-entity.js';
export { SharedNonVerbalEntity } from './shared-non-verbal-entity.js';
export { Figure, FigureImage } from './figure.js';
export { Table } from './table.js';
export { Formula } from './formula.js';
export { NonVerbRep, NON_VERBAL_TYPES } from './non-verb-rep.js';
export { NonVerbalReference } from './non-verbal-reference.js';
export { FigureReference, TableReference, FormulaReference } from './non-verbal-references.js';
export { BibliographyEntry } from './bibliography-entry.js';
export { BibliographyData } from './bibliography-data.js';
export { fetchLocalizedString, localizedStringIsEmpty, localizedStringIsPresent } from './localized-string.js';
